---
- hosts: mysqlmaster
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: generate server-id
      shell: hostname -I | sed -e 's/ \+\([a-z0-9]\+\:\)\+[a-z0-9]\+//' | sed -e 's/ /\n/' | grep -v '^$' | tail -1 | awk -F. '{print $3 * 256 + $4}'
      register: mysql_server_id

    - name: check replication slave status
      mysql_replication: 
        mode: getslave
        ignore_errors: true
        register: slave
  
    - name: get master replication status
      mysql_replication: 
        mode: getmaster 
        login_user: root 
        login_password: root
      delegate_to: "{{ hosts['mysqlmaster'] }}"
      register: replication
      when: slave|failed

    - name: get master binlog file name and binlog position
      mysql_replication:
        mode: getmaster
      register: mysql_master_log_info

- hosts: mysqlslave
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: define master in slave
      mysql_replication: mode=changemaster master_host={{ hosts['mysql-master'] }} master_log_file={{ replication.File }} master_log_pos={{ replication.Position }} master_user=root master_password=root
      when: slave|failed

    - name: start slave
      mysql_replication: mode=startslave
