---
- hosts: mysqlmaster
  vars_files:
    - vars/main.yml
  tasks:
    - name: Copy create_table.sql to mysqlmaster
      copy:
        src: files/create_table.sql
        dest: /tmp
    - name: Copy csv to mysqlmaster
      copy:
        src: files/stockdata.csv
        dest: /tmp

    - name: Retrieve stuff from mysql
      command: >
        mysql --user=root --password=root dow30
        --host=127.0.0.1 --batch --skip-column-names
        --execute="source /tmp/create_table.sql"

    - name: Load sql in data from file
      command: >
        mysql --user=root --password=root dow30
        --host=127.0.0.1 --batch --skip-column-names
        --execute="LOAD DATA LOCAL INFILE '/tmp/stockdata.csv'
                   INTO TABLE stocks
                   COLUMNS TERMINATED BY ','
                   LINES TERMINATED BY '\n'
                   (sym,name,price,html);"
