mysql_root_password: root
mysql_databases:
  - name: dow30
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: dow30
    host: "%"
    password: dow30
    priv: "example_db.*:ALL"
