mysql_root_password: root
mysql_databases:
  - name: dow30
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: root
    host: "%"
    password: root
    priv: "dow30.*:ALL"
mysql_replication_master_host: "{{  hosts['mysqlmaster'] }}"
mysql_replication_user:
  - name: root
    host: "%"
    password: root
